services:
  - type: web
    name: express-claim-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py

  - type: cron
    name: fetch-express-data
    env: python
    schedule: "0 */6 * * *"  # 每 6 小时执行
    buildCommand: pip install -r requirements.txt
    startCommand: python fetch_data.py
